config/routes.rb
Spready::Engine.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users, :module => "devise", :class_name => 'User' if Spready.use_devise?

  namespace :admin do

    resources :forums
    resources :topics
    resources :categories

  end

  resources :forums
  resources :topics
  resources :categories

end

app/controllers/spready/admin/categories_controller.rb
module Spready
  class Admin::CategoriesController < Admin::ApplicationController
    load_and_authorize_resource :class => Spready::Category

    # GET /admin/categories
    # GET /admin/categories.json
    def index
      @admin_categories = Category.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @admin_categories }
      end
    end
  
    # GET /admin/categories/1
    # GET /admin/categories/1.json
    def show
      @admin_category = Admin::Category.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @admin_category }
      end
    end
  
    # GET /admin/categories/new
    # GET /admin/categories/new.json
    def new
      @admin_category = Category.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @admin_category }
      end
    end
  
    # GET /admin/categories/1/edit
    def edit
      @admin_category = Admin::Category.find(params[:id])
    end
  
    # POST /admin/categories
    # POST /admin/categories.json
    def create
      @admin_forum = Forum.find(params[:category][:forum_id])
      @admin_category = @admin_forum.categories.build(params[:category])
      @admin_category.creater = current_user

      respond_to do |format|
        if @admin_category.save
          format.html { redirect_to @admin_category, :notice => 'Category was successfully created.' }
          format.json { render :json => @admin_category, :status => :created, :location => @admin_category }
        else
          format.html { render :action => "new" }
          format.json { render :json => @admin_category.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /admin/categories/1
    # PUT /admin/categories/1.json
    def update
      @admin_category = Admin::Category.find(params[:id])
  
      respond_to do |format|
        if @admin_category.update_attributes(params[:admin_category])
          format.html { redirect_to @admin_category, :notice => 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @admin_category.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /admin/categories/1
    # DELETE /admin/categories/1.json
    def destroy
      @admin_category = Admin::Category.find(params[:id])
      @admin_category.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_categories_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/spready/admin/categories_helper.rb
module Spready
  module Admin::CategoriesHelper
  end
end

app/views/spready/admin/categories/_form.html.erb
<%= semantic_form_for([:admin, @admin_category]) do |f| %>
  <% if @admin_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_category.errors.count, "error") %> prohibited this admin_category from being saved:</h2>

      <ul>
      <% @admin_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :name %>
  <%= select("category", "forum_id", Spready::Forum.all.collect {|f| [ f.name, f.id ] })%>
  <%= f.actions %>
<% end %>

app/views/spready/admin/categories/edit.html.erb
<h1>Editing admin_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_category %> |
<%= link_to 'Back', admin_categories_path %>

app/views/spready/admin/categories/index.html.erb
<h1>Listing admin_categories</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @admin_categories.each do |admin_category| %>
  <tr>
    <td><%= link_to 'Show', admin_category %></td>
    <td><%= link_to 'Edit', edit_admin_category_path(admin_category) %></td>
    <td><%= link_to 'Destroy', admin_category, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Category', new_admin_category_path %>

app/views/spready/admin/categories/new.html.erb
<h1>New admin_category</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_categories_path %>

app/views/spready/admin/categories/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_category_path(@admin_category) %> |
<%= link_to 'Back', admin_categories_path %>