config/routes.rb
Spready::Engine.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users, :module => "devise", :class_name => 'User' if Spready.use_devise?

  namespace :admin do

    resources :forums
    resources :topics
    resources :categories

  end

  resources :forums
  resources :topics
  resources :categories

end

app/controllers/spready/admin/forums_controller.rb
module Spready
  class Admin::ForumsController < Admin::ApplicationController
    load_and_authorize_resource :class => Spready::Forum

    # GET /admin/forums
    # GET /admin/forums.json
    def index
      @admin_forums = Forum.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @admin_forums }
      end
    end
  
    # GET /admin/forums/1
    # GET /admin/forums/1.json
    # TODO: Change this action to display analysis.
    def show
      @admin_forum = Forum.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @admin_forum }
      end
    end
  
    # GET /admin/forums/new
    # GET /admin/forums/new.json
    def new
      @admin_forum = Forum.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @admin_forum }
      end
    end
  
    # GET /admin/forums/1/edit
    def edit
      @admin_forum = Forum.find(params[:id])
    end
  
    # POST /admin/forums
    # POST /admin/forums.json
    def create
      @admin_forum = Forum.new(params[:forum])
      @admin_forum.creater = current_user

      respond_to do |format|
        if @admin_forum.save
          format.html { redirect_to :action => 'index', :notice => 'Forum was successfully created.' }
          format.json { render :json => @admin_forum, :status => :created }
        else
          format.html { render :action => "new" }
          format.json { render :json => @admin_forum.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /admin/forums/1
    # PUT /admin/forums/1.json
    def update
      @admin_forum = Forum.find(params[:id])
  
      respond_to do |format|
        if @admin_forum.update_attributes(params[:forum])
          format.html { redirect_to :action => 'index', :notice => 'Forum was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render :json => @admin_forum.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /admin/forums/1
    # DELETE /admin/forums/1.json
    def destroy
      @admin_forum = Forum.find(params[:id])
      @admin_forum.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_forums_url }
        format.json { head :no_content }
      end
    end
  end
end

app/controllers/spready/forums_controller.rb
require_dependency "spready/application_controller"

module Spready
  class ForumsController < ApplicationController
    # GET /forums
    # GET /forums.json
    def index
      @forums = Forum.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @forums }
      end
    end
  
    # GET /forums/1
    # GET /forums/1.json
    def show
      @forum = Forum.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @forum }
      end
    end
  
    # GET /forums/new
    # GET /forums/new.json
    def new
      @forum = Forum.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @forum }
      end
    end
  
    # GET /forums/1/edit
    def edit
      @forum = Forum.find(params[:id])
    end
  
    # POST /forums
    # POST /forums.json
    def create
      @forum = Forum.new(params[:forum])
  
      respond_to do |format|
        if @forum.save
          format.html { redirect_to @forum, :notice => 'Forum was successfully created.' }
          format.json { render :json => @forum, :status => :created, :location => @forum }
        else
          format.html { render :action => "new" }
          format.json { render :json => @forum.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /forums/1
    # PUT /forums/1.json
    def update
      @forum = Forum.find(params[:id])
  
      respond_to do |format|
        if @forum.update_attributes(params[:forum])
          format.html { redirect_to @forum, :notice => 'Forum was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @forum.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /forums/1
    # DELETE /forums/1.json
    def destroy
      @forum = Forum.find(params[:id])
      @forum.destroy
  
      respond_to do |format|
        format.html { redirect_to forums_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/spready/admin/forums_helper.rb
module Spready
  module Admin::ForumsHelper
  end
end

app/helpers/spready/forums_helper.rb
module Spready
  module ForumsHelper
  end
end

app/views/spready/admin/forums/_form.html.erb
<%= semantic_form_for ([:admin, @admin_forum]) do |f| %>
  <% if @admin_forum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_forum.errors.count, "error") %> prohibited this admin_forum from being saved:</h2>

      <ul>
      <% @admin_forum.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :name, :theme %>
  <%= f.actions %>
<% end %>

app/views/spready/admin/forums/edit.html.erb
<h1>Editing admin_forum</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_forum %> |
<%= link_to 'Back', admin_forums_path %>

app/views/spready/admin/forums/index.html.erb
<h1>Listing admin_forums</h1>

<table>
  <tr>
    <th>name</th>
    <th>theme</th>
    <th>operator</th>
  </tr>

<% @admin_forums.each do |admin_forum| %>
  <tr>
    <td><%= admin_forum.name %></td>
    <td><%= admin_forum.theme %></td>
    <td>
      <%= link_to 'Show', admin_forum %>
      <%= link_to 'Edit', edit_admin_forum_path(admin_forum) %>
      <%= link_to 'Destroy', admin_forum, :method => :delete, :data => { confirm: 'Are you sure?' } %>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Forum', new_admin_forum_path %>

app/views/spready/admin/forums/new.html.erb
<h1>New admin_forum</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_forums_path %>

app/views/spready/admin/forums/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_forum_path(@admin_forum) %> |
<%= link_to 'Back', admin_forums_path %>