config/routes.rb
Spready::Engine.routes.draw do
  
  root :to => 'welcome#index'

  devise_for :users, :module => "devise", :class_name => 'User' if Spready.use_devise?

  namespace :admin do

    resources :forums
    resources :topics
    resources :categories

  end

  resources :forums
  resources :topics
  resources :categories

end

app/controllers/spready/admin/topics_controller.rb
module Spready
  class Admin::TopicsController < ApplicationController
    load_and_authorize_resource :class => Spready::Forum

    # GET /admin/topics
    # GET /admin/topics.json
    def index
      @admin_topics = Topic.all
  
      respond_to do |format|
        format.html # index.html.erb
        format.json { render :json => @admin_topics }
      end
    end
  
    # GET /admin/topics/1
    # GET /admin/topics/1.json
    def show
      @admin_topic = Admin::Topic.find(params[:id])
  
      respond_to do |format|
        format.html # show.html.erb
        format.json { render :json => @admin_topic }
      end
    end
  
    # GET /admin/topics/new
    # GET /admin/topics/new.json
    def new
      @admin_topic = Topic.new
  
      respond_to do |format|
        format.html # new.html.erb
        format.json { render :json => @admin_topic }
      end
    end
  
    # GET /admin/topics/1/edit
    def edit
      @admin_topic = Admin::Topic.find(params[:id])
    end
  
    # POST /admin/topics
    # POST /admin/topics.json
    def create
      @admin_topic = Topic.new(params[:topic])
  
      respond_to do |format|
        if @admin_topic.save
          format.html { redirect_to :action => 'index', :notice => 'Topic was successfully created.' }
          format.json { render :json => @admin_topic, :status => :created, :location => @admin_topic }
        else
          format.html { render :action => "new" }
          format.json { render :json => @admin_topic.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # PUT /admin/topics/1
    # PUT /admin/topics/1.json
    def update
      @admin_topic = Admin::Topic.find(params[:id])
  
      respond_to do |format|
        if @admin_topic.update_attributes(params[:admin_topic])
          format.html { redirect_to @admin_topic, :notice => 'Topic was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render :action => "edit" }
          format.json { render :json => @admin_topic.errors, :status => :unprocessable_entity }
        end
      end
    end
  
    # DELETE /admin/topics/1
    # DELETE /admin/topics/1.json
    def destroy
      @admin_topic = Admin::Topic.find(params[:id])
      @admin_topic.destroy
  
      respond_to do |format|
        format.html { redirect_to admin_topics_url }
        format.json { head :no_content }
      end
    end
  end
end

app/helpers/spready/admin/topics_helper.rb
module Spready
  module Admin::TopicsHelper
  end
end

app/views/spready/admin/topics/_form.html.erb
<%= semantic_form_for([:admin, @admin_topic]) do |f| %>
  <% if @admin_topic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin_topic.errors.count, "error") %> prohibited this admin_topic from being saved:</h2>

      <ul>
      <% @admin_topic.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= f.inputs :title, :content, :category %>
  <%= f.actions %>
<% end %>

app/views/spready/admin/topics/edit.html.erb
<h1>Editing admin_topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin_topic %> |
<%= link_to 'Back', admin_topics_path %>

app/views/spready/admin/topics/index.html.erb
<h1>Listing admin_topics</h1>

<table>
  <tr>
    <th>title</th>
    <th>content</th>
    <th>user</th>
    <th>operator</th>
  </tr>

<% @admin_topics.each do |admin_topic| %>
  <tr>
    <td><%= admin_topic.title %></td>
    <td><%= admin_topic.content %></td>
    <td><%= admin_topic.user.email %></td>
    <td><%= link_to 'Show', admin_topic %>
    <%= link_to 'Edit', edit_admin_topic_path(admin_topic) %>
    <%= link_to 'Destroy', admin_topic, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Topic', new_admin_topic_path %>

app/views/spready/admin/topics/new.html.erb
<h1>New admin_topic</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_topics_path %>

app/views/spready/admin/topics/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_topic_path(@admin_topic) %> |
<%= link_to 'Back', admin_topics_path %>